version: '3.7'

services:
  tsnodedocker:
    restart: always
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
    container_name: tsnodedocker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run start
    environment:
      APP_ENV: production
    networks:
      - daapi
      
networks:
  daapi:
    driver: bridge
