version: '3.7'

services:
  tsnodedocker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: tsnodedocker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev