version: "3.7"

services:
  tsnodedocker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: tsnodedocker
    expose:
      - "443"
    ports:
      - "4000:4000"
    command: npm run start
    environment:
      APP_ENV: test
    networks:
      - daapi
  aliyunsts:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    working_dir: /home/node/app/script/sts-app-server-node
    volumes:
      - ./script/sts-app-server-node:/home/node/app/script/sts-app-server-node
    container_name: aliyunsts
    expose:
      - "9000"
    ports:
      - "9000:9000"
    command: node index.js
    environment:
      APP_ENV: development
    networks:
      - daapi

networks:
  daapi:
    driver: bridge
