version: "3.7"

services:
  tsnodedocker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./node_modules:/home/node/app/node_modules
    container_name: tsnodedocker
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: >
      bash -c "/home/node/app/bin/run-web.sh"
    environment:
      APP_ENV: development
    networks:
      - daapi

networks:
  daapi:
    driver: bridge
