/** Declaration file generated by dts-gen */

export = push_umeng;

declare class push_umeng {
  constructor(...args: any[]);

  getBathList(...args: any[]): void;

  getSign(...args: any[]): void;

  push(...args: any[]): void;

  pushList(...args: any[]): void;

  pushSingle(...args: any[]): void;

  queryPushStatus(...args: any[]): void;

  sleep(...args: any[]): void;

  uploadFile(...args: any[]): void;

  static createFile(...args: any[]): void;

  static md5(...args: any[]): void;
}
